### ISSUE TITLE
Error during installation of mvlearn

### ISSUE THREAD

**Issue by ieserbes** [mvlearn/mvlearn#321]
## Template Code
```
!pip3 install mvlearn
```

## Error message
```
Collecting mvlearn
  Using cached mvlearn-0.5.0-py3-none-any.whl (2.1 MB)
Collecting matplotlib<=3.3.4,>=3.0.0 (from mvlearn)
  Using cached matplotlib-3.3.4.tar.gz (37.9 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Traceback (most recent call last):
        File "C:\Users\isile\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\isile\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\isile\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\isile\AppData\Local\Temp\pip-build-env-oy8xvqix\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\isile\AppData\Local\Temp\pip-build-env-oy8xvqix\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\isile\AppData\Local\Temp\pip-build-env-oy8xvqix\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\isile\AppData\Local\Temp\pip-build-env-oy8xvqix\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 52, in <module>
        File "C:\Users\isile\AppData\Local\Temp\pip-install-10ljockj\matplotlib_dc8c84400ec4424fa96a0971d102f4c9\versioneer.py", line 1410, in get_version
...
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

## Your Environment
* Python version: Python 3.12.0
* mvlearn version: -
* matplotlib version: 3.8.1

**Comment by agramfort** [comment]
I am not sure Python 3.12 is already supported. I would use python 3.11 for
now.

**Comment by ieserbes** [comment]
> I am not sure Python 3.12 is already supported. I would use python 3.11 for now.
> […](#)
> Message ID: ***@***.***>

Thank you for your prompt response, I also tried to install it with python 3.9. But I got the same error. My operating system is Windows.

**Comment by agramfort** [comment]
pip install matplotlib
or
pip install numpy

works?

**Comment by ieserbes** [comment]
Yes, they worked well. 

![Screenshot 2023-11-12 150232](https://github.com/mvlearn/mvlearn/assets/111044699/1b48bbef-ea45-498e-9a0b-d47eb34f0806)

**Comment by agramfort** [comment]
you could try to do :

pip install mvlearn --no-deps

then try to import mvlearn, add one by one the package that are missing and
see which one is problematic.

**Comment by ieserbes** [comment]
This is interesting. 
I installed the mvlearn as you suggested with the command "pip install mvlearn --no-deps" and then import it "import mvlearn" (please see the image). I didn't encounter a problem. 
![Screenshot 2023-11-18 113040](https://github.com/mvlearn/mvlearn/assets/111044699/604c3305-ec77-4160-a81d-068391d3a762)
And I did perform some example analysis and it worked.
![Screenshot 2023-11-18 113437](https://github.com/mvlearn/mvlearn/assets/111044699/f2958cd8-f5fa-4dc6-9595-83631a707400)
But when I use the !pip install mvlearn command only it does still give the same error above. 
Nevertheless the command "pip install mvlearn --no-deps" solved my issue. 
I also would like to thank you for this extremely useful package. It is also easy to implement.
